### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by btholt** [reddit/styleguide#25]
Does it make sense to have a universal [.editorconfig](http://editorconfig.org/) for reddit? I think it'd go a long way to standardizing some of the code styles according to each of the varying language's needs.

**Comment by umbrae** [comment]
I'm +1 on it, don't think it would really hurt.

**Comment by xiongchiamiov** [comment]
Huh, I thought we had one for reddit/reddit already.

I've never bothered setting up the plugin for my editor yet, but I'm still +1 on making one of these; it's certainly better than those vim-specific hints that require turning on unsafe execution modes.

**Comment by btholt** [comment]
Already merged.
